[build]
builder = "nixpacks"
buildCommand = "npm install --force && npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 300

[env]
NODE_ENV = "production"
PORT = "3000"
DOMAIN = "pa11y.wookongmarketing.com" 